// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication12.DAL.Database;

namespace WebApplication12.DAL.Migrations
{
    [DbContext(typeof(Data))]
    [Migration("20220206035337_start12")]
    partial class start12
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication12.DAL.Entity.Branch", b =>
                {
                    b.Property<int>("Branc_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manager")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Branc_Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("WebApplication12.DAL.Entity.Customer", b =>
                {
                    b.Property<int>("Custo_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Custo_Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WebApplication12.DAL.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("expire_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<DateTime>("production_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebApplication12.DAL.Entity.Product_order", b =>
                {
                    b.Property<int>("ord_id")
                        .HasColumnType("int");

                    b.Property<int>("pro_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("ord_id", "pro_id");

                    b.HasIndex("pro_id");

                    b.ToTable("product_Orders");
                });

            modelBuilder.Entity("WebApplication12.DAL.Entity.order", b =>
                {
                    b.Property<int>("orderr_num")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("customer_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("totalPrice")
                        .HasColumnType("int");

                    b.HasKey("orderr_num");

                    b.HasIndex("customer_id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebApplication12.DAL.Entity.Product_order", b =>
                {
                    b.HasOne("WebApplication12.DAL.Entity.order", "orders")
                        .WithMany("pro_ord")
                        .HasForeignKey("ord_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication12.DAL.Entity.Product", "product")
                        .WithMany("pro_ord")
                        .HasForeignKey("pro_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("orders");

                    b.Navigation("product");
                });

            modelBuilder.Entity("WebApplication12.DAL.Entity.order", b =>
                {
                    b.HasOne("WebApplication12.DAL.Entity.Customer", "customer")
                        .WithMany("orders")
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("WebApplication12.DAL.Entity.Customer", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("WebApplication12.DAL.Entity.Product", b =>
                {
                    b.Navigation("pro_ord");
                });

            modelBuilder.Entity("WebApplication12.DAL.Entity.order", b =>
                {
                    b.Navigation("pro_ord");
                });
#pragma warning restore 612, 618
        }
    }
}
